### ISSUE TITLE
Request for sxhkdrc

### ISSUE THREAD

**Issue by sudo-chan** [leetApe/new-bspdots#1]
Hey! I really love your setup. Could you please also share your sxhkdrc? 

Also, what do these lines do? If possible could you please show a short GIF/Vid of it? 

https://github.com/leetApe/new-bspdots/blob/7a737aed63b643529555b0da94d90dd1b50ad74e/bspwmrc#L38-L39

**Comment by leetApe** [comment]
Thank you! 

I've already added the sxhkdrc to  the repo.

I use ksuperkey to bind my mod key to alt + f1 to launch rofi. Unfortunately, I couldn't provide a short video for it since I am not currently using this set up.

**Comment by sudo-chan** [comment]
Thanks!
